### ISSUE TITLE
 Connection pool problem between ASP.NET and SQL Server

### ISSUE THREAD

**Issue by ungureanuraluca15** [ehm2097/web-sql#5] opened 2018-06-22 09:09 UTC
It seems that at some certain periods of time, it throws an exception : "Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached" .

**Comment by ehm2097** [comment] 2018-06-25 19:00
Issue confirmed. Cause seems to be an incorrect assumption about how connection pooling works in .Net. Fix in progress

**Comment by ehm2097** [comment] 2018-06-27 05:40
Fixed in v1.1.2

**Closed as completed** 2018-06-27 05:40 UTC
